test/navigation-commands.spec.js

Add tests for class Redirect and for function isNavigationCommand.

test(navigation-commands): add tests

---

test/activation.spec.js

create basic tests for activation module CanDeactivatePreviousStep

test(activation): added tests for activation

---

src/router.js

fix(router): get queryParams route-recognizer results

---

config.js
package.json
src/app-router.js
src/navigation-context.js

add events for
-processing
-complete
-error
-cancelled
fix issue in navigation-context that
was causing pipeline to finish before commit
closes aurelia/router#24

feat(router): add lifecycle events

---

src/router.js
test/router.spec.js

Requires aurelia/route-recognizer#6

Minor route config validation improvements

---

src/router.js
test/navigation-commands.spec.js

This covers the API addition needed for #69.

Add navModel.setTitle method

---

src/router.js

fix(router): correctly handle absolute URLs when navigating

---

src/router.js
test/router.spec.js

fix(router): handle navigating to the empty string in a child router

---

src/navigation-instruction.js

This change merges ancestor instruction params with the current instruction params only for the argument passed to `activate()`.
BREAKING CHANGE: Parent params are no longer available via the `$parent` property. Parent params can be accessed via `navigationInstruction.parentInstruction.params`. Injected `*childRoute` param is no longer available on the params object passed to `activate()`.
Discussed in aurelia/framework#119

feat(navigation-instruction): merge ancestor instruction params into current params

---

src/router.js
src/util.js

A couple small path-related bug fixes

---

src/navigation-instruction.js

refactor(NavigationInstruction): adds constructor parameter type information
refactor(NavigationInstruction): adds method return type information
In these PRs I am not submitting the changes to dist because I am operating under the assumption that the dist files will be updated automatically by a build server.  If that is not the case and dist pushes are desired let me know.  That being said, when I build locally I get a lot of unrelated changes to the dist... I'm not sure why.

refactor(NavigationInstruction): list all properties on the class directly

---

src/router.js

Slowly working towards making TypeScript definitions more useful and error free.

refactor(Router): list all properties on the class directly

---

src/router.js

Made a new PR with the changes in https://github.com/aurelia/router/pull/143

chore(all): add types

---

src/router.js

I have added the `currentInstruction` property to the `Router` class, so that it is added to the generated d.ts file.

chore(Router): added currentInstruction property

---

build/tasks/doc.js
src/interfaces.js
src/nav-model.js
src/router-configuration.js
src/router.js

Also cleaned up some type annotations.

doc(router): add doc comments on public router and router-configuration API

---

package.json

need to make sure that the appropriate gulp-typedoc-extractor is used

feat(docs): generate api.json from .d.ts file

---

src/navigation-commands.js

Parameter options in constructor of Redirect class was changed to be optional.

d.ts fix - options parameter in Redirect class constructor is optional

---

src/router.js

fix(router): reset configuration promise in reset()

---

src/router-configuration.js

Typescript definition fix

---

src/navigation-context.js

this will add the properties to the typescript defintions

chore(context): add properties for d.ts generation

---

package.json
src/pipeline.js

fix(pipeline): Fix type annotations on pipeline next parameter

---

src/navigation-commands.js
test/navigation-commands.spec.js

This is missing from the router today.

Added support for redirect to a named route via RedirectToRoute.

---

src/pipeline-provider.js

https://github.com/aurelia/router/issues/332

feat(PipelineProvider): add methods for removing pipeline steps

---

src/pipeline.js

https://github.com/aurelia/router/issues/326

Flagged parameters as optional

---

src/router.js

better error messages for issue #370

better error messages

---

doc/article/en-us/router-configuration.md

@EisenbergEffect Here is the PR for the router configuration article.

doc(router-configuration): add router configuration article

---

src/activation.js
src/interfaces.js
src/navigation-commands.js

Added `RoutableComponent` interface to `interfaces.js`(wasn't sure where it should go) and `NavigationCommand` interface to `navigation-commands.js` - see #375.
Also added `activationStrategy` to `RouteConfig`.

feat(interfaces.js): add RoutableComponent

---

src/router.js

fix(router): add navigationStrategy to cloned route config

---

doc/article/en-US/router-configuration.md

Example code doesn't work this fixes
https://github.com/aurelia/documentation/issues/279

fix broken example code

---

src/navigation-instruction.js

Ref: https://github.com/aurelia/router/issues/397
Update NavigationInstruction TypeScript definition to define router.

fix(tsd): define router property in NavigationInstruction

---

doc/article/en-US/router-configuration.md
src/app-router.js
src/router-configuration.js
test/app-router.spec.js

Proposal of solution for enhancement:
https://github.com/aurelia/router/issues/431

Fallback route config

---

doc/article/en-US/router-configuration.md

adds info on how to update the title when the locale changes

docs(i18n): update title on locale change

---

doc/article/en-US/router-configuration.md
src/interfaces.js

Addresses:
https://github.com/aurelia/documentation/issues/314
https://github.com/aurelia/documentation/issues/310
https://github.com/aurelia/documentation/issues/316
https://github.com/aurelia/documentation/issues/317
https://github.com/aurelia/router/issues/447

documentation changes: layouts, swap order, view ports

---

src/app-router.js
src/router.js

The added properties are useful when deciding on behaviour during the routing lifecycle.
Closes aurelia/router#449.

feat(router) add isExplicitNavigation and isExplicitNavigationBack

---

src/interfaces.js
src/navigation-plan.js

Added the ActivationStrategy interface to describe the shape of the activationStrategy object that enumerates route activation strategies.

feat(type declarations): improve type of activationStrategy

---

src/activation.js
test/activation.spec.js

fix(activation): Deactivate child viewModels when replacing a parent 

---

doc/article/en-US/router-configuration.md

Adding some description for router.isNavigating due to the problem I saw in gitter for some developers.

doc( router.isNavigating ) a description has been added

---

doc/article/en-US/router-configuration.md
src/interfaces.js

doc(activation-strategy): improve activation strategy doc

---

src/interfaces.js

Fix https://github.com/aurelia/router/issues/523

doc(interfaces): fix layoutModel typescript type

---

src/router.js

- Clarified navigation options meaning in router.js
- Explained url generation options

Improved router documentation

---

doc/article/en-US/router-configuration.md

https://github.com/aurelia/router/issues/522

doc(router-configuration): refactor code example

---

src/app-router.js
src/router-configuration.js
src/router.js
test/app-router.spec.js

Revert "feat(router config): ignoreUnknownRoutes option"

---

src/router-configuration.js
src/router.js
src/util.js
test/router.spec.js

Cherry picked from [this commit](https://github.com/aurelia/router/pull/576/commits/49fd46bf51da1dee877b9c85660492c62dfb1d05) by @fkleuver. 
Closes #509 #576

fix(router): Split routes in addRoute

---

src/router-configuration.js

fix(router-configuration): merge options instead of assign in exportRouter

---

doc/article/en-US/router-configuration.md
src/navigation-instruction.js
src/router-configuration.js
src/router.js
test/navigation-instruction.spec.js

feat(router-config): Make title separator configurable

---

doc/article/en-US/router-configuration.md

Closes https://github.com/aurelia/framework/issues/883

doc(router-configuration): add Webpack configuration docs

---

src/navigation-plan.js

fix(redirect): do not use Promise.reject on redirect

---

test/router.spec.js

Fixes https://github.com/aurelia/router/issues/433.
Requires https://github.com/aurelia/route-recognizer/pull/30.

test(router): test multiple identical patterns

---

src/navigation-plan.js
test/navigation-plan.spec.js

All of the following will now work:
```
// Redirects 'first' to 'second/0'
{ route: 'first', redirect: 'second/0' }
// Redirects 'first/1' to 'second/1'
{ route: 'first/:foo', redirect: 'second/:foo' }
// Redirects 'first/1/2' to 'second'
{ route: 'first/:foo/:bar', redirect: 'second/:baz' }
{ route: 'second/:id?' }
```
closes #607

fix(navigation-plan): Accept parameters in a redirect config

---

doc/article/en-US/router-configuration.md

Fixing up numerous grammatical errors and a couple of typos.

docs(router): typos and grammatical errors
