- src/router.js
- test/router.spec.js
routes with nav:false were still being included in router.navigation
routes that contain nav:false will no longer be included
> fix(router): do not add routes with nav=false

- src/index.js
the replace, invoke lifecycle, and no_change strategies
needed to be exported so that they could be used
> fix(router): export navigation strategies

- src/router.js
This PR fixes the following issue:
When pushState is enabled, navigating between routes duplicates/nests url fragments, here's an example:
1. Starting at /
2. Navigate to /route1
Expected:
Link to /route1 in the navigation is still /route1
Link to /route2 in the navigation is still /route2
Actual result:
Link to /route1 is /route1/route1
Link to /route2 is /route2/route2
Subsequent navigations keep nesting under the current location
> fix(router): url fragments duplicated on subsequent navigations between routes when using pushState

- src/app-router.js
When an anchor has nested elements, like the following example:
<a href="/">
<i class="icon-home"></i>
<span>Some text</span>
</a>
When clicking on the inner elements (icon or span), the link is not being handled, and a full page reload happens instead
> fix(router): link click handler not triggering when clicking on a nested element inside an anchor

- src/app-router.js
- src/index.js
- src/navigation-context.js
- src/pipeline-provider.js
- src/pipeline.js
- src/route-filters.js
- src/router-configuration.js
- src/router.js
This adds support for small named pipelines, named
route-filters, which can easily be added at given points
in the pipeline. By default, two such pipelines are
created, "authorize", and "modelbind". These acts as
"placeholders" in the pipeline, where the end user
can easily insert their own steps.
Fixes #26
> feat(router): add support for named pipelines

- src/router.js
- test/router.spec.js
* Support navigating to absolute paths from any router instance
* Add `router.navigateToRoute` convenience method, equivalent to `router.navigate(router.generate(...))`
* Minor code cleanup
fixes #52
> Router navigation improvements

- src/app-router.js
- src/route-loading.js
This change fixes a crash if a truthy non-promise value is returned by configureRouter().
> fix(app-router): handle non-promise return values from configureRouter

- src/router.js
- test/router.spec.js
This fixes what I believe is a bug; the following code causes the `validateRouteConfig` to throw an `Error` because it's currently expecting either `moduleId` or `redirect`.  
```
this.router.configure(config => {
config.title = 'Aurelia';
config.map('',
{
nav: true,
title: 'Welcome',
viewPorts: {
'default': {
moduleId: './welcome/welcome'
},
'dataTables': {
moduleId: './plugins/dataTables/sample'
}
}
});
});
```
The included unit test validates this case.
> fix to support viewPorts in routes without moduleId or redirect + unit test

- src/pipeline.js
fixes #85
AppRouter's [pipeline error handling](https://github.com/aurelia/router/blob/master/src/app-router.js#L72-L75) is designed to handle Promises that *resolve* with error results (not rejections). When `next.reject` returns a Promise *rejection* the error is intercepted by [catch handlers](https://github.com/aurelia/router/blob/master/src/navigation-plan.js#L83) in a couple places, which wrap the result in a second cancelled result and resolve. The `result` in AppRouter's continuation ends up being a `cancelled` result, whose `output` is an inner `rejected` result, which is handled as a nav cancellation instead of an error.
An alternative solution might be to keep the `Promise.reject()`, remove some or all of the `.catch()` handlers, and move `AppRouter`'s pipeline error handling …
> fix(pipeline): fix bug preventing errors in pipeline steps from being handled

- src/router.js
Trying to add a navigationStrategy to a route throws the following validation error:
`You must have at least a route and a moduleId, redirect, or viewPorts. at validateRouteConfig`
I've added the condition to the validation and made other changes to make the following route configuration work:
```
{
route: ['', 'welcome'], nav: true, title: 'Welcome',
navigationStrategy: function(instruction) {
instruction.config.moduleId = 'welcome';
}
}
```
The changes I've made fix some of the issues I encountered, but I'm not 100% sure it's the way that this is supposed to work, please review.
> fix(router): using navigationStrategy throws a validation error

- src/router-configuration.js
- src/router.js
BREAKING CHANGE: This is a breaking change to anyone relying on the `RouterConfiguration` to derive values for required route config properties. All config properties must now be specified explicitly.
> Replace route config property derivations with stricter validation

- src/navigation-instruction.js
This change fixes a navigation error when using query strings in combination with default routes in child routers.
fixes #106
> fix(navigation-instruction): query string causes error in child routers

- src/navigation-plan.js
When checking if the routes parameters changed when navigating between views, the logic does not take into account when the next route parameters does not contain parameters from the previous one.
It works fine in this example: 
Current view params: `{ param1: 'someValue' }`
Next view params: `{ param1: 'someValue', param2: 'anotherValue' }`
It does not work in the opposite direction:
Current view params: `{ param1: 'someValue', param2: 'anotherValue' }`
Next view params: `{ param1: 'someValue' }`
because it iterates through only the next route parameters, comparing `param1` without noticing that `param2` is now missing compared to the previous view.
There might be a smarter way to compare the two objects, so it might be better refactored, but wasn't sure of how the wildcards should be …
> fix(router): incorrectly comparing routes parameter values in navigation plan

- src/navigation-instruction.js
- src/navigation-plan.js
- src/route-loading.js
- src/router.js
- src/util.js
This change fixes several issues with configs specifying redirects.
* The pipeline now properly handles route configs specifying redirects in child routers. Previously this was only handled for the top-level routes in `BuildNavigationPlanStep`.
* A redirect location of '' is now accepted.
* Redirect locations are now resolved relative to the navigation instruction rather than assumed to be relative.
* Query strings are now preserved across redirects.
fixes #103
> fix(navigation-plan): handle redirects in child router configs

- src/router.js
Strip leading slash from route paths before registering child handlers to avoid adding bad route paths to child recognizers.
fixes #116
> fix(router): a route with path '/' breaks handleUnknownRoutes

- config.js
- package.json
- src/app-router.js
* All navigations now raise 3 events: `processing`, (`success` | `error` | `canceled`), and `complete`.
* All navigation events include the same event args: `{ instruction, result }`, except for `processing`, which omits the result property.
* A maximum of 10 instruction executions are attempted before giving up with a navigation error.
* Unexpected return values from the pipeline are now handled as error results instead of crashing.
> Refactor dequeueInstruction to improve nav events and error handling

- src/router-configuration.js
Fixes #146.
I'm not sure if empty properties will make it to the d.ts or not (they are compiled out when transpiling to ES5 I believe).  I could default them to null, though I'm worried that some area of the code may treat null and undefined differently.  Alternatively, #146 could be fixed by adding a setter for `title` (`unknownRouteConfig` already has one).  I prefer this method, as it makes it clear at the top of the class what all the properties of it are, but perhaps people shouldn't be reading from these, only setting them in which case the public interface is really set-only, so a function for each would be better.
> Lists all properties on the class directly.

- src/pipeline-provider.js
Add a Pipeline Step to allow code to run after the View has been
inserted into the DOM.
We use some jquery plugins that cache elements against a global object
to save editing these plugins which makes updates difficult, we use the
commitcomplete pipline step to reset the values on the global object
> Added a "commitcomplete" pipeline step

- src/app-router.js
- src/navigation-commands.js
- src/navigation-instruction.js
- src/pipeline.js
- src/router.js
We were previously using `import core from core-js` which generates d.ts that do not match the corejs d.ts. This is now updated to `import * as core 'core-js'`, which resolves TypeScript compilation warnings.
closes aurelia/framework#177
> fix(router): Use correct import for core-js

- src/app-router.js
Typo causes an exception which is swallowed up and not displayed in console.
> Fix typo 'resut'

- src/router.js
- test/router.spec.js
ensureConfigured returns a Promise that resolves when the router is configured. Useful for easily building functionality that must wait for async router configurations.
Supports fix for aurelia/framework#158
> feat(router): add ensureConfigured method

- src/app-router.js
- src/route-loading.js
- src/router.js
- test/app-router.spec.js
- test/router.spec.js
This change moves handling of async router config callbacks into Router.configure to resolve a race condition when using multiple viewPorts. Async configuration was previously handled externally in app-router and route-loading, but that code failed to block subsequent calls from configuring multiple times. Router.configure() now handles async callbacks, setting isConfigured immeditely to allow callers to check state.
BREAKING CHANGES:
* Router.configure() now always returns a Promise, and is no longer chainable.
* Router.configure() now applies the configuration in a Promise continuation, so it is not safe to assume that the router will be configured synchronously when the configuration callback is synchronous.
fixes #213
> fix(router): properly handle async router configurations

- src/activation.js
BREAKING CHANGE: Activation code returning string values to abort
activation will need to perform their own comparison and return a
boolean
> feat(activation): remove support for string affirmations from activation

- src/navigation-instruction.js
This avoids lengthy warning when using bluebird library for promises.
> Returning null to signal that we didn't forget to return

- src/interfaces.js
The property "navModel" exists on the RouteConfig object, but it was missing from the interface, breaking Typescript. It is now added.
Fixes #285.
> fix(router): add NavModel to RouteConfig interface

- src/navigation-plan.js
When a route does not configure all available viewports, the navigation plan will crash. Now, the navigation plan will log a helpful error with the missing viewport and the affected route.
Fixes #241.
> fix(router): log helpful error on missing viewport

- src/pipeline-provider.js
- src/route-filters.js
- src/router-configuration.js
- test/route-filters.spec.js
Pipeline slots have been renamed: 'modelbind' is 'preActivate', 'precommit' is 'preRender', and 'postcomplete' is 'postRender'. Sugar methods have been added to support the new names. RouteFilterContainers now support aliases in order to preserve backwards compatibility. Tests have been added for 'route-filters.js'.
Fixes #295.
> refactor(router): rename pipeline slots

- src/route-filters.js
- test/route-filters.spec.js
Lookup instantiation was running in the wrong part of the router lifecycle. This fixes the issue by making the lookup a module-level variable.
> fix(router): fix regression in route pipelines

- config.js
- package.json
- src/router.js
- src/util.js
- test/router.spec.js
Adds an extra boolean argument to `router.generate` to specify whether or not to generate an absolute URI.
Fixes #88.
> feat(router): generate absolute URI from router

- src/interfaces.js
- src/router.js
- test/router.spec.js
Router is case sensitive by default, if you need to set some route as case sensitive you can add `caseSensitive: true` property to the route configuration.
in order to close https://github.com/aurelia/router/issues/271
> fix(router): router is case sensitive by default

- src/activation.js
feat(router): observables in lifecycle
When an Observabe (or something approximating one, as per the ECMA proposal) is returned from the activate hook, the router will wait until at least one value has moved through the Observable (or if the Observable completes while empty) before rendering the view.
Implements #336
> feat(router): observables in lifecycle

- src/router.js
- test/router.spec.js
`router.refreshNavigation` should update the href of navigation model when route changes. Static routes (defined in config) do not need to update this property. The check for a static href was looking at the nav href instead of the config href.
closes aurelia/router#246
> fix(router): change refresh navigation to check config for static href not nav model href

- src/router.js
- test/router.spec.js
This is in reference to #366.
Router will throw an error if a route with the same name in addRoute
> fix(router): ensure routes have distinct names

- doc/article/en-US/router-configuration.md
Hi all,
I just tried to make wildcard routes to work, had a look at the documentation and saw that this route won't work:
```javascript
{ route: 'files*path',       name: 'files',      moduleId: 'files/index',   href:'#files',   nav: true },
```
I've searched around and found this comment from @bryanrsmith:
https://github.com/aurelia/router/issues/297#issuecomment-188447021
I derived from that comment that the configuration mentioned above should rather look like this:
```javascript
{ route: 'files/*path',       name: 'files',      moduleId: 'files/index',   href:'#files',   nav: true },
```
I've tried that in my app and it works.
This PR is my attempt to fix the router documentation.
If you'd rather like to adjust the router implementation to match the documentation, please feel free to …
> doc(router): fix wildcard router config and documentation

- doc/article/en-US/router-configuration.md
Updates the example, closes #404 . The example was correct, but misleading. The function passed to `.mapUnknownRoutes()` was also used for `.navigationStrategy`. Removed the unrelated navigation strategy part.
> doc(router-configuration): simplify handle unknown routes examples

- doc/article/en-US/router-configuration.md
Current documentation points to the layout property on RouterView (which does not exist),
this fixes that problem.
> Fix wrong attribute on router-view example

- doc/article/en-US/router-configuration.md
fix router/doc/article/en-US/router-configuration.md: unexpected token when building the module
> Syntax error when using the example provided in docs

- doc/article/en-US/router-configuration.md
The TypeScript examples that shows how to setup a function to map unknown routes has an error in it. At the moment, it returns an object containing a `moduleId` string. However, this leads to a compile error, which makes sense if we examine the typings:
``` typescript
mapUnknownRoutes(config: string | RouteConfig | ((instruction: NavigationInstruction) => string | RouteConfig | Promise<string | RouteConfig>)): RouterConfiguration;
```
The specific function overload used is expected to return a `string`, not an object. The ES6 example returns the same object, so either the typings are wrong or there is also a bug in the ES6 example.
> doc(typescript): fix mapUnknownRoutes Typescript compile error

- src/app-router.js
I have a route that simply redirects to a different module, but I wasn't receiving any published events from the router with the instruction details.
This allows me to hook in on the instruction that is being re-directed to without having to worry about why there is a conditional on the other events that get published.
> Publishes an inner instruction resolve

- src/pipeline.js
Change PipelineStep.prototype.run return type to Promise because next(), next.complete() return Promise.
> doc(pipeline): fix return type

- src/navigation-instruction.js
- test/navigation-instruction.spec.js
Fixes #27
When a child router is checking for a parents baseUrl it does not take
in to account that the parent may be routing to the empty route.  This
PR adds a spec to cover that scenario and a basic implementation.
> chore(empty-routes): fix child urls with emptys

- src/navigation-instruction.js
- test/activation.spec.js
Consider the following scenario:
The same view-model can be reused in different view ports (for example in a two-column layout). The rendering might slightly differ depending on which view port is it being rendered in. How should the view-model access this information?
Added viewport's name to config object being sent to `activate` / `deactivate`
> feat(viewport): add viewport name to life cycle arguments

- doc/article/en-US/router-configuration.md
Both _Internationalizing Titles_ and _Configuring a Fallback Route_ currently have section id 12. This changes _Configuring a Fallback Route_ to 13.
> doc(router): fix section number for Fallback Route

- test/activation.spec.js
I removed a test that would erroneously fail. The test was checking that a plan with a childNavigationInstruction property that returned true or false on canDeactivate would continue or cancel respectively. The mock childNavigationInstruction was missing the required childRouter property, and so it was giving erroneous results.
The following test, 'with router and currentInstruction', actually includes coverage for the very same feature. Therefore, removing the erroneous test was sufficient.
> test(activation.spec): Remove obsolete activation test

- src/navigation-instruction.js
- test/navigation-instruction.spec.js
This addresses issues #435 and #486 and extends pull request https://github.com/aurelia/router/pull/497.
fragment may or may not be encoded but path will always be decoded. In order to compare fragment and path - fragment has to be decoded first.
This will cover any use-cases where fragment is not encoded, partially encoded or fully encoded.
This will affect router.baseUrl which will now be encoded. It will also affect the href parameter in the router.navigation array.
This means it may not be exactly the same as navigationInstruction.fragment for any of the routes if the URL isn't fully encoded to begin with.
> fix(navigation-instruction): getBaseUrl() to return correct URL for encodable chars

- src/activation.js
- test/activation.spec.js
This enables the consumer to inspect the navigation instructions and make a decision on whether or not a route can be deactivated based on the incoming navigation instructions.
Closes #493
> feat(activation): call can/Deactivate with navigationInstruction

- src/navigation-instruction.js
- src/router.js
- test/router.spec.js
bubble up the current router parent chain for the first defined unknown route handler if one does not exists on the current router
feature #443
> feat(router): enable parent chain unknown route handlers

- src/navigation-instruction.js
The waitToSwap variable was not properly being passed to child routes' _commitChanges(), which introduced a timing issue where a child router's baseUrl was not updated before it was bound. This commit adds the variable back in.
Resolves https://github.com/aurelia/router/issues/306
Resolves https://github.com/aurelia/router/issues/552
Resolves https://github.com/aurelia/templating-router/issues/46
> fix(navigation-instruction): Wait to swap child routes

- package.json
- src/navigation-plan.js
- src/route-loading.js
- src/router-configuration.js
- src/router.js
Before, all viewports had to be specified in every route. This feature enables omitting a viewport or specifying a default viewport.
Any viewport configuration with `moduleId: null` will use the default viewport configuration. Initially, the default viewport configuration is an empty view and view model pair. You can override this by passing a viewport configuration to the `useDefaultViewPort()` method on `RouterConfiguration`.
```javascript
configureRouter(config, router) {
// this means that whenever the menu viewport is populated with { moduleId: null } in the router, it will populate with the 'defaultMenu' module.
config.useDefaultViewPort({ menu: { moduleId: PLATFORM.module('defaultMenu') } });
}
```
If a route is missing a viewport configuration, then that route will remain …
> feat(router): Support optional and default view ports

- package.json
- src/navigation-plan.js
- src/route-loading.js
Makes viewports optional in route configuration. Enables configuring viewports to be either empty or contain previous module.
Depending on aurelia/templating-router/optional-viewports.
Partially closes aurelia/router/issues/482.
> feat(router): optional viewports

- package.json
- src/navigation-plan.js
- src/route-loading.js
- src/router-configuration.js
- src/router.js
Adds viewPortDefaults to RouterConfiguration so that optional viewports in route configurations can have a default module.
Depending on aurelia/templating-router#64 and aurelia/router#535.
Closes aurelia/router#482.
> feat(router): viewport defaults

- src/app-router.js
- src/router.js
- test/app-router.spec.js
- test/router.spec.js
The added properties allows deciding on behaviour during the routing lifecycle based on user navigation choices.
Depending on PR aurelia/history-browser/page-state.
Closes aurelia/router#436.
> feat(router) add navigation flags

- src/app-router.js
- src/router-configuration.js
- src/router.js
- test/app-router.spec.js
Implements the ignoreUnknownRoutes option mentioned in issue https://github.com/aurelia/router/issues/527.
> feat(router config): ignoreUnknownRoutes option

- src/router.js
Attempt to resolve #573 .
Added a property in router. It is used in NavigationInstruction and RouterConfiguration
> fix(router): define title property

- src/navigation-plan.js
- test/navigation-plan.spec.js
- test/router.spec.js
allow redirect to contain token parameters for router config
this closes feature request #483
> feat(router): redirect with token parameters

- src/router-configuration.js
Changes on RouterConfiguration:
- Specify the properties with type "any": `instructions`, `options`, `unknownRouteConfigs`, `viewPortDefaults`.
- Fix the incorrect type of `pipelineSteps` (should be array of objects with `name`, `step`)
- Specify the parameters and return type of `useViewPortDefaults()`
`gulp build` and `karma start` returned no errors.
> feat(type declarations): improve type of RouterConfiguration

- src/interfaces.js
- src/pipeline.js
- src/router.js
type NavigationResult = PipelineResult | boolean;
ref: https://discourse.aurelia.io/t/checking-for-candeactivate-before-navigatetoroute/51/2
> fix(navigation): add NavigationResult type

- src/app-router.js
- test/app-router.spec.js
Navigation command (eg. redirect) in child route navigation strategy was not working, when parent route was also using a navigation strategy
Fixes https://github.com/aurelia/router/issues/588
> fix(app-router): await navigation result

- doc/article/en-US/router-configuration.md
There is currently no place in the router-configuration documentation that describes how to resolve moduleId when using webpack.
Closes https://github.com/aurelia/framework/issues/883
> doc(router-configuration): add webpack configuration

- src/navigation-plan.js
- src/route-loading.js
This causes #480 to re-appear until a better handling for cancellations exists – but it’s still better than the errors caused by improper handling of redirects at the moment.
There’s no easy way to call `next.cancel` from all places that can create a redirect. I’d suggest changing redirects to add a magic value to an `Error` (eg. `error.redirect = new Redirect(…)`) and rejecting with that.
But this would require changes in several places that check for `output instanceof Error` to determine the kind of result.
> Fix error introduced in 487c33d5 (when trying to fix #480)

- src/interfaces.js
- src/router.js
Flow doesn't support type aliasing so the new interface was breaking `d.ts` generation. We haven't released any new typing with this type alias.
@EisenbergEffect @davismj
> fix(typings): Revert aliasing interface

- src/activation.js
- src/app-router.js
- src/pipeline-provider.js
- src/router.js
- test/activation.spec.js
To handle this, I've added a new parameter to the router called `couldDeactivate` which is set to true whenever the CanDeactivatePreviousStep completes and is reset on every navigation. If a redirect is returned from the CanActivateNextStep, then this value will be true and it is used to build a special pipeline that skips the CanDeactivatePreviousStep on the next pipeline run.
fixes #45
> fix: Prevent running CanDeactivatePreviousStep twice in same navigation

- src/activation-strategy.ts
- src/app-router.ts
- src/aurelia-router.ts
- src/interfaces.ts
- src/navigation-commands.ts
- src/navigation-instruction.ts
- src/navigation-plan.ts
- src/pipeline-provider.ts
- src/pipeline.ts
- src/route-loader.ts
- src/router-configuration.ts
- src/router.ts
- src/step-activation.ts
- src/step-build-navigation-plan.ts
- src/step-commit-changes.ts
- src/step-load-route.ts
- src/utilities-activation.ts
- src/utilities-route-loading.ts
- test/route-loading/load-component.spec.ts
- test/route-loading/load-route-step.spec.ts
This PR focuses on re-organizing files and classes to make it easier to discover. Along with linting fixes and big function breakdown, such as `_buildNavigationPlan` in `navigation-plan.ts`
Another refactoring target was to have more local variables over long property chain access with verbose name, this should help greatly with minification.
After this, the focus will be fixing bug and incorporating existing PRs
@EisenbergEffect @davismj @fkleuver 
Also add an overload for `NavigationInstruction.prototype.addViewPortInstruction` to accept an options object, to open a path for future feature related to static view model. It looks like this
```ts
/**
* Adds a viewPort instruction. Returns the newly created instruction based on parameters
*/
addViewPortInstruction(initOptions: …
```
> refactor(all): better discover-ability, files re-org
